---
title: "Cut vs Binomial"
author: "Feifan Cao"
date: "4/29/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libarry

```{r}
library(ggplot2)
library(dplyr)
```

## Data set

```{r}
combined_results <- readRDS("cut_from_shuffling.RDS")
```

## Compare Cut result and Binomial Distribution
```{r}
# Graphic
ggplot(combined_results, aes(x=top_half_number, y=after_stat(density))) +
  geom_histogram(binwidth=1, color="white") +
  geom_point(data = data.frame(num_on_top = 0:52) %>% mutate(pmf = dbinom(num_on_top, 52, 0.5)),
             aes(x = num_on_top, y = pmf), color = "red") +
  geom_density(color='blue') +
  labs(y= "Proportion of Shuffles", x = "Number of Cards in Top Cuts") +
  ggtitle('Empirical Proportion vs. Binomial Distribution')

# Hypothesis test Prep
table(combined_results$top_half_number) #18 20 21 22 23 24 25 26 27 28 29 30 31 32 33 38 /  1  3  6 19 27 41 54 48 76 90 62 41 17  2  2  1 
numbers <- c(18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 38)
counts  <- c(1, 3, 6, 19, 27, 41, 54, 48, 76, 90, 62, 41, 17, 2, 2, 1)
all_numbers <- 0:52
all_counts  <- rep(0, 53)
present_indices <- match(numbers, all_numbers)
all_counts[present_indices] <- counts

# Chi-Squared goodness of fit test
chisq.test(all_counts, p=dbinom(0:52, 52, 0.5))

# hypothesis test for the theta > 0.5
sum_of_y <- sum(combined_results$top_half_number)
n <- length(combined_results$top_half_number)
prop.test(sum_of_y, 52*n, p=0.5, alternative = 'greater')
prop.test(sum_of_y, 52*n, p=0.5)
```

